### ISSUE TITLE
FileNotFoundException on loading solution

### ISSUE THREAD

**Issue by yawnston** [ppumkin/PrestoCoverage#10]
After installing your extension, when I try to open a solution in Visual Studio, I get the following error message:

![image](https://user-images.githubusercontent.com/18127325/47290025-d44c1c00-d5fd-11e8-902f-a9ea9098699d.png)

Here is the relevant part of the log:

> <entry>
    <record>964</record>
    <time>2018/10/22 11:23:09.011</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.CodeAnalysis.Workspaces, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.CodeAnalysis.Workspaces, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos;&#x000D;&#x000A;   at PrestoCoverage.CommentTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
  </entry>

The extension then doesn't work, running tests doesn't show any coverage.

My friend with Visual Studio Professional version doesn't have these issues and the extension works fine.

Microsoft Visual Studio Community 2017 
Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Version 4.7.03056

**Comment by ppumkin** [comment]
@yawnston Does Visual Studio Community 15.8+ exist?
The DLL it is trying to load is a Rosyln helper that I use to get various information about the project.. it should be bundled with the Extension but it seems like it just doesn't like VS 2017 v17 

I am just wondering how come you are not on 15.8 yet?

**Comment by ppumkin** [comment]
Thanks for letting me know


I think the problem is because your VS is version 15.7 and that DLL requires 15.8+


I will update my docs to make sure people know that.


________________________________

**Comment by yawnston** [comment]
@ppumkin I updated to 15.8.7 and your extension now works. I think it's safe to say that was the problem.
